=== shaun95/variational-diffwave/utils/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "instance": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "args": {
                    "type": "object"
                }
            },
            "required": [
                "type",
                "args"
            ]
        }
    },
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "arch": {
            "$ref": "#/definitions/instance"
        },
        "dataset": {
            "$ref": "#/definitions/instance"
        },
        "optimizer": {
            "$ref": "#/definitions/instance"
        },
        "lr_scheduler": {
            "$ref": "#/definitions/instance"
        },
        "data_loader": {
            "type": "object",
            "properties": {
                "batch_size": {
                    "type": "integer"
                },
                "shuffle": {
                    "type": "boolean"
                }
            },
            "required": [
                "batch_size",
                "shuffle"
            ]
        },
        "trainer": {
            "type": "object",
            "properties": {
                "save_dir": {
                    "type": "string"
                },
                "log_dir": {
                    "type": "string"
                },
                "eval_file": {
                    "type": "string"
                },
                "cum_steps": {
                    "type": "integer"
                },
                "amp_enabled": {
                    "type": "boolean"
                },
                "n_fft": {
                    "type": "integer"
                },
                "hop_length": {
                    "type": "integer"
                },
                "n_mels": {
                    "type": "integer"
                },
                "sr": {
                    "type": "integer"
                },
                "eval_interval": {
                    "type": "integer"
                },
                "train_T": {
                    "type": "integer"
                },
                "eval_T": {
                    "type": "integer"
                },
                "extra_monitor": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "minimize_var": {
                    "type": "boolean"
                },
                "with_amp": {
                    "type": "boolean"
                }
            },
            "required": [
                "save_dir",
                "log_dir",
                "eval_file",
                "cum_steps",
                "eval_interval",
                "n_fft",
                "hop_length",
                "n_mels",
                "sr",
                "train_T",
                "eval_T",
                "extra_monitor",
                "with_amp"
            ]
        }
    },
    "required": [
        "name",
        "arch",
        "dataset",
        "optimizer",
        "lr_scheduler",
        "data_loader",
        "trainer"
    ]
}

=== shaun95/variational-diffwave/continuous_64ch.json
{
    "name": "DiffWave",
    "arch": {
        "type": "DiffWave",
        "args": {
            "T": 1000
        }
    },
    "dataset": {
        "type": "RandomWAVDataset",
        "args": {
            "data_dir": "~/data-disk/Datasets/LJ/LJSpeech-1.1/wavs/",
            "size": 12000000,
            "segment": 16000,
            "deterministic": false
        }
    },
    "optimizer": {
        "type": "Adam",
        "args": {
            "lr": 2e-4
        }
    },
    "lr_scheduler": {
        "type": "ReduceLROnPlateau",
        "args": {
            "factor": 0.3,
            "patience": 1000000,
            "verbose": true
        }
    },
    "data_loader": {
        "batch_size": 12,
        "shuffle": false,
        "drop_last": false,
        "num_workers": 4,
        "prefetch_factor": 4,
        "pin_memory": true
    },
    "trainer": {
        "save_dir": "saved/",
        "log_dir": "runs/",
        "eval_file": "~/data-disk/Datasets/LJ/LJSpeech-1.1/wavs/LJ001-0001.wav",
        "cum_steps": 1,
        "n_fft": 1024,
        "hop_length": 256,
        "n_mels": 80,
        "sr": 22050,
        "eval_interval": 10000,
        "train_T": 0,
        "eval_T": 50,
        "extra_monitor": [
            "kld",
            "ll",
            "loss_T"
        ],
        "with_amp": true,
        "max_log_snr": 23,
        "min_log_snr": -3.6
    }
}

=== shaun95/variational-diffwave/discrete_100steps_64ch.json
{
    "name": "DiffWave",
    "arch": {
        "type": "DiffWave",
        "args": {
            "T": 100
        }
    },
    "dataset": {
        "type": "RandomWAVDataset",
        "args": {
            "data_dir": "~/data-disk/Datasets/LJSpeech-1.1/wavs/",
            "size": 16000000,
            "segment": 16000
        }
    },
    "optimizer": {
        "type": "Adam",
        "args": {
            "lr": 2e-4
        }
    },
    "lr_scheduler": {
        "type": "ReduceLROnPlateau",
        "args": {
            "factor": 0.3,
            "patience": 1000000,
            "verbose": true
        }
    },
    "data_loader": {
        "batch_size": 16,
        "shuffle": true,
        "drop_last": false,
        "num_workers": 4,
        "prefetch_factor": 4,
        "pin_memory": true
    },
    "trainer": {
        "save_dir": "saved/",
        "log_dir": "runs/",
        "eval_file": "~/data-disk/Datasets/LJSpeech-1.1/wavs/LJ001-0001.wav",
        "cum_steps": 1,
        "n_fft": 1024,
        "hop_length": 256,
        "n_mels": 80,
        "sr": 22050,
        "eval_interval": 10000,
        "train_T": 100,
        "eval_T": 25,
        "extra_monitor": [
            "kld",
            "ll",
            "loss_T"
        ],
        "minimize_var": false,
        "with_amp": true
    }
}
